### ISSUE TITLE
How to train a custom classifier in this docker ?

### ISSUE THREAD

**Issue by technoartista** [IBM/MAX-Inception-ResNet-v2#13]
How to train a custom classifier in this docker ? Can you add an option to train aswell?

**Comment by MLnick** [comment]
Hi there - apologies for the delay in responding. 

Currently we don't have any options for training related to this model. It is something on our longer-term roadmap to look into making models such as this one trainable with custom data (whether from scratch or transfer learning), however at present we are not able to provide any estimate on when that may be enabled.
